# Generated by Django 4.2 on 2023-04-21 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_goal', models.IntegerField(default=500000, validators=[django.core.validators.MaxValueValidator(500000)])),
                ('employee_goal', models.IntegerField(default=100000, validators=[django.core.validators.MaxValueValidator(500000)])),
                ('today_goal', models.IntegerField(default=100000, validators=[django.core.validators.MaxValueValidator(100000)])),
            ],
            options={
                'verbose_name_plural': 'Static Values',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profit', models.IntegerField(default=0)),
                ('user_id', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
