# Generated by Django 4.2 on 2023-04-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticvalue',
            name='employee_goal',
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='staticvalue',
            name='global_goal',
            field=models.IntegerField(default=500000),
        ),
        migrations.AlterField(
            model_name='staticvalue',
            name='today_goal',
            field=models.IntegerField(default=100000),
        ),
    ]
