# Generated by Django 4.2 on 2023-04-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_staticvalue_employee_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticvalue',
            name='token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
