# Generated by Django 4.2 on 2023-05-15 15:10

import colorfield.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_staticvalue_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticvalue',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 15, 15, 10, 31, 69132)),
        ),
        migrations.AddField(
            model_name='staticvalue',
            name='pizza_sound',
            field=models.FileField(default='static/sounds/pizza.mp3', upload_to='static/sounds/'),
        ),
        migrations.AddField(
            model_name='staticvalue',
            name='sale_sound',
            field=models.FileField(default='static/sounds/sale.mp3', upload_to='static/sounds/'),
        ),
        migrations.AddField(
            model_name='staticvalue',
            name='show_users_15_and_20_percent',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staticvalue',
            name='success_color',
            field=colorfield.fields.ColorField(default='#529653', image_field=None, max_length=18, samples=None),
        ),
        migrations.AddField(
            model_name='staticvalue',
            name='use_start_of_month',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='goal',
            field=models.IntegerField(default=500000),
        ),
    ]
