# Generated by Django 4.2 on 2023-05-15 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_staticvalue_date_staticvalue_pizza_sound_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticvalue',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 15, 15, 12, 52, 406720)),
        ),
    ]
