# Generated by Django 4.2 on 2023-05-15 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_staticvalue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticvalue',
            name='date_turn_on',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='staticvalue',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 15, 15, 22, 8, 800374)),
        ),
    ]
