# Generated by Django 4.2.5 on 2023-09-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_user_show_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_users',
            field=models.BooleanField(default=True),
        ),
    ]
