# Generated by Django 4.2.5 on 2023-09-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_user_show_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='show_users',
        ),
        migrations.AddField(
            model_name='staticvalue',
            name='show_employees',
            field=models.BooleanField(default=True),
        ),
    ]
