# Generated by Django 4.2.5 on 2023-09-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_remove_staticvalue_show_employees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='show_employees',
        ),
        migrations.AddField(
            model_name='staticvalue',
            name='show_employees',
            field=models.BooleanField(default=True),
        ),
    ]
