# Generated by Django 4.2.5 on 2023-09-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_user_show_employees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staticvalue',
            name='show_employees',
        ),
    ]
