# Generated by Django 4.2.5 on 2023-09-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_staticvalue_show_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticvalue',
            name='show_employees',
            field=models.BooleanField(default=True),
        ),
    ]
