# Generated by Django 4.2.5 on 2023-11-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_staticvalue_show_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticvalue',
            name='message',
            field=models.TextField(default='', max_length=150),
        ),
    ]
