# Generated by Django 4.2.5 on 2023-11-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_staticvalue_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticvalue',
            name='message',
            field=models.TextField(blank=True, default='', max_length=300, null=True),
        ),
    ]
