# Generated by Django 4.2.5 on 2023-11-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_staticvalue_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
