# Generated by Django 4.2.5 on 2023-11-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_user_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.CharField(blank=True, default='http://lepo.pythonanywhere.com/', max_length=255, null=True),
        ),
    ]
