# Generated by Django 4.2.5 on 2023-11-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_user_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='url',
        ),
    ]
