# Generated by Django 4.2.5 on 2024-03-23 04:30

import colorfield.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0029_remove_user_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaticValue2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("global_goal", models.IntegerField(default=500000)),
                ("employee_goal", models.IntegerField(default=100000)),
                ("today_goal", models.IntegerField(default=100000)),
                ("token", models.CharField(default="", max_length=200)),
                ("date", models.DateField(default=datetime.datetime.now)),
                ("use_start_of_month", models.BooleanField(default=True)),
                (
                    "success_color",
                    colorfield.fields.ColorField(
                        default="#529653", image_field=None, max_length=25, samples=None
                    ),
                ),
                ("show_users_15_and_20_percent", models.BooleanField(default=True)),
                (
                    "pizza_sound",
                    models.FileField(
                        default="static/sounds/pizza.mp3", upload_to="static/sounds/"
                    ),
                ),
                (
                    "sale_sound",
                    models.FileField(
                        default="static/sounds/sale.mp3", upload_to="static/sounds/"
                    ),
                ),
                ("date_turn_on", models.BooleanField(default=True)),
                ("show_employees", models.BooleanField(default=True)),
                (
                    "message",
                    models.TextField(blank=True, default="", max_length=300, null=True),
                ),
            ],
            options={
                "verbose_name_plural": "Static Values",
            },
        ),
        migrations.CreateModel(
            name="User2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("profit", models.IntegerField(default=0)),
                ("user_id", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                ("goal", models.IntegerField(default=500000)),
            ],
        ),
        migrations.AlterModelOptions(
            name="staticvalue",
            options={},
        ),
    ]
