# Generated by Django 4.2.5 on 2024-03-23 05:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0030_staticvalue2_user2_alter_staticvalue_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User2",
            new_name="UsersElle2",
        ),
        migrations.RenameModel(
            old_name="StaticValue2",
            new_name="ValuesElle2",
        ),
    ]
