# Generated by Django 4.2.5 on 2024-03-25 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0031_rename_user2_userselle2_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ValuesElle2",
            new_name="StaticValueEnglishDistrict",
        ),
        migrations.RenameModel(
            old_name="StaticValue",
            new_name="StaticValueVictory",
        ),
        migrations.RenameModel(
            old_name="UsersElle2",
            new_name="UserEnglishDistrict",
        ),
        migrations.RenameModel(
            old_name="User",
            new_name="UserVictory",
        ),
        migrations.AlterModelOptions(
            name="staticvalueenglishdistrict",
            options={
                "verbose_name_plural": (
                    "Static Values Victory",
                    "Static Values English District",
                    "Users Victory",
                    "Users English District",
                )
            },
        ),
    ]
